### ISSUE TITLE
'ValueError: too many values to unpack' when creating Cluster

### ISSUE THREAD

**Issue by Taffer** [getsamsa/samsa#107]
Just trying to see if samsa will meet my needs... samsa==0.3.11, kazoo==2.0 (both installed via pip).

No idea if I've installed the wrong versions of something or what, but just creating a Samsa Cluster object throws a ValueError. Any ideas/solutions?

```python
>>> zk = kazoo.client.KazooClient(hosts='my-host:2181')
>>> zk.start()
>>> cluster = samsa.cluster.Cluster(zk)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/samsa/cluster.py", line 44, in __init__
    self.brokers = BrokerMap(self)
  File "/usr/lib/python2.7/site-packages/samsa/brokers.py", line 45, in __init__
    self._node_path, self._configure
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 288, in __init__
    self._get_children()
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 333, in _get_children
    result = self._func(children)
  File "/usr/lib/python2.7/site-packages/samsa/brokers.py", line 66, in _configure
    broker = Broker(self.cluster, id_=broker_id)
  File "/usr/lib/python2.7/site-packages/samsa/brokers.py", line 146, in __init__
    self._node_path, self._configure
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 130, in __init__
    self._get_data()
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 204, in _get_data
    self._log_func_exception(data, stat, event)
  File "/usr/lib/python2.7/site-packages/kazoo/recipe/watchers.py", line 163, in _log_func_exception
    result = self._func(data, stat)
  File "/usr/lib/python2.7/site-packages/samsa/brokers.py", line 160, in _configure
    creator, self.__host, port = data.split(':')
ValueError: too many values to unpack
```

**Comment by kbourgoin** [comment]
Hi @Taffer. What version of Kafka are you using?  That looks like it might be from trying to use 0.8.x when samsa only supports the 0.7.x branch. We're working on 0.8.2 support and plan on releasing it within the next month or two.

**Comment by Taffer** [comment]
Ah, that's probably it then, I think I've got 0.8.x on this dev box. Thanks @kbourgoin!
